### PR TITLE
add desktop submenu to theme

### PR DESCRIPTION
**Pull request by mvanlaar**
in the default.ascx change the line

<dnn:MENU MenuStyle="nav/main" NodeSelector="*,0,0" runat="server" />
to:
<dnn:MENU MenuStyle="nav/nav-main-submenu" NodeSelector="*,0,1" runat="server" />

### CODE REVIEW

**Comment by iJungleboy** [comment]
Could you tell us more what this does? Just so we don't have to guess from the code?

**Comment by mvanlaar** [comment]
It wil create a submenu voor the topmenu. There is no styling in this pull request included.

image

**Comment by eXistenZe** [comment]
There is no nav-main-submenu in my folder.

**Comment by eXistenZe** [comment]
Only now I figured why my nav was not showing for me. It's missing the "*".
`<dnn:MENU` MenuStyle="nav/nav-main-submenu" NodeSelector="*,0,1" runat="server" />

**Pull request merged**
